[package]
name = "sourcec"
version = "0.1.0"
authors = ["Bobbie Soedirgo <bobbie@soedirgo.dev>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm11-0"] }
serde_json = "1.0"
