#!/usr/bin/env node
const { createContext } = require("js-slang")
const { parse } = require("js-slang/dist/parser/parser")

const { readFileSync } = require('fs')

const source = readFileSync(0, 'utf-8')
const context = createContext(1)

const estree = parse(source, context)
if (!estree) {
    throw new Error("Failed to parse Source program")
}

console.log(JSON.stringify(estree))
